name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1.1.0
      with:
        target: esp32s3

    - name: Archive build output artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          build/bootloader/bootloader.bin
          build/partition_table/partition-table.bin
          build/${{ github.event.repository.name }}.bin
